name: homework1
dependencies:
  - cycler=0.10.0=py36_0
  - freetype=2.8
  - libpng=1.6.34
  - matplotlib=2.2.2
  - mkl=2018.0.3=1
  - nose=1.3.7
  - numpy=1.14.3
  - openssl=1.0.2o
  - pandas=0.23.0
  - pip=10.0.1=py36_0
  - pyparsing=2.2.0=py36_0
  - pyqt=5.9.2
  - python=3.6.5
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.4=py36_0
  - qt=5.9.5
  - readline=7.0
  - scikit-learn=0.19.1
  - scipy=1.1.0
  - setuptools=39.2.0=py36_0
  - sip=4.19.8
  - six=1.11.0
  - sqlite=3.23.1
  - tk=8.6.7
  - wheel=0.31.1=py36_0
  - zlib=1.2.11
  - pip:
    - untangle==1.1.1

